
           <?php include $template1.'.phtml'?>
           
           <?php include $template.'.phtml' ?>   
           

            <!-- FOOTER -->
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 widget-footer col-sm-3">
                            <h5>About Store</h5>
                            <img src="images/basic/logo-lite.png" class="img-responsive space10" alt=""/>
                            <p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus</p>
                            <div class="clearfix"></div>
                            <ul class="f-social">
                                <li><a href="https://www.facebook.com" class="fa fa-facebook"></a></li>
                                <li><a href="https://www.twitter.com" class="fa fa-twitter"></a></li>
                                <li><a href="https://feedburner.google.com" class="fa fa-rss"></a></li>
                                <li><a href="mailto:email@website.com" class="fa fa-envelope"></a></li>
                                <li><a href="https://www.pinterest.com" class="fa fa-pinterest"></a></li>
                                <li><a href="https://www.instagram.com" class="fa fa-instagram"></a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Latest Tweets</h5>
                            <div class="tweet-info">
                                <div id="twitterfeed"></div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Product tags</h5>
                            <ul class="widget-tags">
                                <li><a href="./categories-grid.html">fashion</a></li>
                                <li><a href="./categories-grid.html">sports</a></li>
                                <li><a href="./categories-grid.html">business</a></li>
                                <li><a href="./categories-grid.html">news</a></li>
                                <li><a href="./categories-grid.html">night</a></li>
                                <li><a href="./categories-grid.html">freedom</a></li>
                                <li><a href="./categories-grid.html">design</a></li>
                                <li><a href="./categories-grid.html">miracle</a></li>
                                <li><a href="./categories-grid.html">gallery</a></li>
                                <li><a href="./categories-grid.html">collection</a></li>
                                <li><a href="./categories-grid.html">pen</a></li>
                                <li><a href="./categories-grid.html">pants</a></li>
                                <li><a href="./categories-grid.html">jeans</a></li>
                                <li><a href="./categories-grid.html">photos</a></li>
                                <li><a href="./categories-grid.html">oscar</a></li>
                                <li><a href="./categories-grid.html">smile</a></li>
                                <li><a href="./categories-grid.html">love</a></li>
                                <li><a href="./categories-grid.html">sunshine</a></li>
                                <li><a href="./categories-grid.html">luxury</a></li>
                                <li><a href="./categories-grid.html">forever</a></li>
                                <li><a href="./categories-grid.html">inlove</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Newsletter</h5>
                            <p>Sign up for our newsletter and promotions</p>
                            <form class="newsletter">
                                <input type="text" placeholder="Enter your email address here.">
                                <button type="submit">Subscribe !</button>
                            </form>
                        </div>
                    </div>
                </div>
            </footer>

            <!-- FOOTER COPYRIGHT -->
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 col-sm-7">
                            <ul class="flinks">
                                <li><a href="./index.html">Site Map</a></li>
                                <li><a href="./index.html">Search Terms</a></li>
                                <li><a href="./index.html">Advanced Search</a></li>
                                <li><a href="./index.html">Orders and Returns</a></li>
                                <li><a href="./index.html">Customer Service</a></li>
                            </ul>
                            <br>
                            <p>Copyright 2015 &middot; Designed & Developed by <a href="#">jThemes Studio.</a> All rights reserved</p>
                        </div>
                        <div class="col-md-5 col-sm-5">
                            <img src="images/basic/payment.png" class="pull-right img-responsive payment" alt=""/>
                        </div>
                    </div>
                </div>
            </div>  

        </div>

        <!-- Newsletter -->
        

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                    <div class="row">
                        <div class="col-md-5 col-sm-6">
                            <div class="owl-carousel sync1">
                                <div class="item"> <img src="images/products/single/1-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/2-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/3-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/4-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/1-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/2-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/3-small.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/4-small.jpg" alt=""> </div>
                            </div>

                            <div class="owl-carousel sync2">
                                <div class="item"> <img src="images/products/single/1.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/2.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/3.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/4.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/1.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/2.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/3.jpg" alt=""> </div>
                                <div class="item"> <img src="images/products/single/4.jpg" alt=""> </div>
                            </div>
                        </div>
                        <div class="col-md-7 col-sm-6">
                            <div class="product-single">
                                <div class="ps-header">
                                    <span class="badge offer">-50%</span>
                                    <h3>Product fashion</h3>
                                    <div class="ratings-wrap">
                                        <div class="ratings">
                                            <span class="act fa fa-star"></span>
                                            <span class="act fa fa-star"></span>
                                            <span class="act fa fa-star"></span>
                                            <span class="act fa fa-star"></span>
                                            <span class="act fa fa-star"></span>
                                        </div>
                                        <em>(6 reviews)</em>
                                    </div>
                                    <div class="ps-price"><span>$ 200.00</span> $ 99.00</div>
                                </div>

                                <div class="ps-stock">
                                    Available: <a href="#">In Stock</a>
                                </div>
                                <div class="sep"></div>
                                <div class="ps-color">
                                    <p>Color<span>*</span></p>
                                    <a class="black" href="#" onclick="return false;"></a>
                                    <a class="red" href="#" onclick="return false;"></a>
                                    <a class="yellow" href="#" onclick="return false;"></a>
                                    <a class="darkgrey" href="#" onclick="return false;"></a>
                                    <a class="litebrown" href="#" onclick="return false;"></a>
                                </div>
                                <div class="space10"></div>
                                <div class="row select-wraps">
                                    <div class="col-md-7 col-sm-7">
                                        <p>Size<span>*</span></p>
                                        <select>
                                            <option>XL</option>
                                            <option>XXL</option>
                                            <option>XXXL</option>
                                        </select>
                                    </div>
                                    <div class="col-md-5 col-sm-5">
                                        <p>Quantity<span>*</span></p>
                                        <select>
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                            <option>5</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="space20"></div>
                                <div class="share">
                                    <span>
                                        <a href="#" class="fa fa-heart-o" onclick="return false;"></a>
                                        <a href="#" class="fa fa-signal" onclick="return false;"></a>
                                        <a href="#" class="fa fa-envelope-o" onclick="return false;"></a>
                                    </span>
                                    <div class="addthis_native_toolbox"></div>
                                </div>
                                <div class="space20"></div>
                                <div class="sep"></div>
                                <a class="btn-color" href="#">Add to Bag</a>
                                <a class="btn-black" href="#">Go to Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="backtotop"><i class="fa fa-chevron-up"></i></div>



        <!-- Javascript -->
        <script src="www/js/jquery.js"></script>

       

        <script src="www/js/bootstrap.min.js"></script>        
        <script src="www/plugin/owl-carousel/owl.carousel.min.js"></script>
        <script src="www/js/bs-navbar.js"></script>
        <script src="www/js/vendors/isotope/isotope.pkgd.js"></script>
        <script src="www/js/vendors/slick/slick.min.js"></script>
        <script src="www/js/vendors/tweets/tweecool.min.js"></script>
        <script src="www/js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script src="www/js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
        <script src="www/js/jquery.sticky.js"></script>
        <script src="www/js/jquery.subscribe-better.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script src="www/js/vendors/select/jquery.selectBoxIt.min.js"></script>
        <script src="www/js/main.js"></script>

    </body>
</html>