


            <!--  produits -->
            <div class="featured-products">
                <div class="container">
                    <div class="row">
                        <h5 class="heading"><span>Produits</span></h5>
                       
                        <div id="isotope" class="isotope">

                            <?php foreach($produits as $prod){ ?>
                            <div class="isotope-item">
                                <div class="product-item">
                                    <div class="item-thumb">
                                        <img src="<?php echo $prod['image'];?>" class="img-responsive" alt=""/>
                                    </div>
                                    <div class="product-info">
                                        <h4 class="product-title"><a href="index.php?action=produit&id=<?php echo $prod['id'];?>"><?php echo $prod['titre']; ?></a></h4>
                                        <span class="product-price"><?php echo $prod['prix'];?> </span>
                                        
                                    </div>
                                </div>
                            </div>
                         
                            <?php } ?>



                            
                        </div>
                    </div>
                </div>
            </div>

           
           

           